# <center>2. S&P Global - Data preparation </center>

**************************************************************************************************
@autor: Diego Babativa <br />
@date: 2022-10 <br />
@Description: This Data preparation notebook is the second data analysis approach. Here We are going to able to do the feature engeneering analysis <br />
**************************************************************************************************

### 1. Loading pre-processed data

In [14]:
import pandas as pd

df = pd.read_parquet('../../data/proccessed/interview_dataset_processed.parquet')
df.shape

(1000, 26)

In [15]:
categorical_variables = (
    list(df.drop(columns=['date_on_production'])
           .select_dtypes(exclude=['float','number'])
           .columns)
        )
categorical_variables

['treatment_company', 'operator']

In [16]:
df['treatment_company'] = df['treatment_company'].str.replace(' ', '_').str.replace('treatment_company', 'treat_comp')
df['operator'] = df['operator'].str.replace(' ', '_').str.replace('operator', 'oper')

In [17]:
df[categorical_variables]

    treatment_company operator
0        treat_comp_1   oper_1
1        treat_comp_2   oper_2
2        treat_comp_3   oper_1
3        treat_comp_4   oper_1
4        treat_comp_5   oper_3
..                ...      ...
995     treat_comp_10   oper_6
996     treat_comp_23   oper_4
997      treat_comp_4   oper_4
998      treat_comp_5  oper_22
999      treat_comp_9  oper_14

[1000 rows x 2 columns]

In [21]:
df_dummies_cat = pd.get_dummies(
        df[categorical_variables],
        drop_first=True,
        prefix={'treatment_company':'tc',
                'operator':'opt',}
        )
df_dummies_cat

,tc_treat_comp_10,tc_treat_comp_11,tc_treat_comp_12,tc_treat_comp_13,tc_treat_comp_14,tc_treat_comp_15,tc_treat_comp_16,tc_treat_comp_17,tc_treat_comp_18,tc_treat_comp_19,...,opt_oper_33,opt_oper_34,opt_oper_35,opt_oper_36,opt_oper_4,opt_oper_5,opt_oper_6,opt_oper_7,opt_oper_8,opt_oper_9
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df_features = (
    df.drop(columns=categorical_variables)
    .join(df_dummies_cat, how='inner')
)

In [24]:
list(df_features.columns)

['azimuth',
 'md_(ft)',
 'tvd_(ft)',
 'date_on_production',
 'footage_lateral_length',
 'well_spacing',
 'porpoise_deviation',
 'porpoise_count',
 'shale_footage',
 'acoustic_impedance',
 'log_permeability',
 'porosity',
 'poisson_ratio',
 'toc',
 'vcl',
 'p-velocity',
 's-velocity',
 'youngs_modulus',
 'isip',
 'pump_rate',
 'total_number_of_stages',
 'proppant_volume',
 'proppant_fluid_ratio',
 'production',
 'tc_treat_comp_10',
 'tc_treat_comp_11',
 'tc_treat_comp_12',
 'tc_treat_comp_13',
 'tc_treat_comp_14',
 'tc_treat_comp_15',
 'tc_treat_comp_16',
 'tc_treat_comp_17',
 'tc_treat_comp_18',
 'tc_treat_comp_19',
 'tc_treat_comp_2',
 'tc_treat_comp_20',
 'tc_treat_comp_21',
 'tc_treat_comp_22',
 'tc_treat_comp_23',
 'tc_treat_comp_24',
 'tc_treat_comp_25',
 'tc_treat_comp_26',
 'tc_treat_comp_27',
 'tc_treat_comp_28',
 'tc_treat_comp_29',
 'tc_treat_comp_3',
 'tc_treat_comp_30',
 'tc_treat_comp_31',
 'tc_treat_comp_4',
 'tc_treat_comp_5',
 'tc_treat_comp_6',
 'tc_treat_comp_7',
 'tc_treat_comp_8',
 'tc_treat_comp_9',
 'opt_oper_10',
 'opt_oper_11',
 'opt_oper_12',
 'opt_oper_13',
 'opt_oper_14',
 'opt_oper_15',
 'opt_oper_16',
 'opt_oper_17',
 'opt_oper_18',
 'opt_oper_19',
 'opt_oper_2',
 'opt_oper_20',
 'opt_oper_21',
 'opt_oper_22',
 'opt_oper_23',
 'opt_oper_24',
 'opt_oper_25',
 'opt_oper_26',
 'opt_oper_27',
 'opt_oper_28',
 'opt_oper_29',
 'opt_oper_3',
 'opt_oper_30',
 'opt_oper_31',
 'opt_oper_32',
 'opt_oper_33',
 'opt_oper_34',
 'opt_oper_35',
 'opt_oper_36',
 'opt_oper_4',
 'opt_oper_5',
 'opt_oper_6',
 'opt_oper_7',
 'opt_oper_8',
 'opt_oper_9']

In [27]:
df_features.isna().sum()

azimuth                   0
md_(ft)                   0
tvd_(ft)                  0
date_on_production        0
footage_lateral_length    0
                         ..
opt_oper_5                0
opt_oper_6                0
opt_oper_7                0
opt_oper_8                0
opt_oper_9                0
Length: 89, dtype: int64

In [28]:
df_features = df_features.drop(columns=['date_on_production'])

In [30]:
df_features.to_parquet('../../data/features/interview_dataset_features_v1.parquet')